# Generated by Django 5.0.4 on 2026-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MAINTENEUR', 'Mainteneur'), ('CHEF_PROJET', 'Chef de Projet'), ('DIRECTEUR_TECHNIQUE', 'Directeur Technique'), ('DIRECTEUR_GENERAL', 'Directeur Général'), ('CLIENT', 'Client')], default='MAINTENEUR', max_length=30),
        ),
    ]
