# Generated by Django 6.0.3 on 2026-06-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('nombre_panneaux', models.PositiveIntegerField()),
                ('frequence_nettoyage', models.PositiveIntegerField(help_text='Fréquence en jours')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('responsable_maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
