# Generated by Django 5.0.4 on 2026-07-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_historique_id_alter_nettoyage_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(choices=[('SATISFAIT', 'Satisfait'), ('NEUTRE', 'Neutre'), ('INSATISFAIT', 'Insatisfait')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('confirme', models.BooleanField(default=False)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('nettoyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis_client', to='maintenance.nettoyage')),
            ],
        ),
    ]
